#' Example single-cell counts data
#'
#' Example single-cell gene expression counts data containing 9 discrete cell types/groups (gps)
#' generated by Splatter.
#'
#' @format A matrix with 5,000 rows (genes) and 500 columns (cells):
#' @source {Simulated single-cell data generated by Splatter} \url{https://doi.org/10.1186/s13059-017-1305-0}
#' @examples data(counts_gps)
"counts_gps"

#' Example bulk data
#'
#' Example bulk gene expression data generated by aggregating cells from counts_gps single-cell data.
#'
#'
#' @format A matrix with 5,000 rows (genes) and 5 columns (bulk samples)
#' @source {Simulated bulk data generated by aggregating cell types/groups (gps) in counts_gps}
#' @examples data(bulk_gps)
"bulk_gps"

#' Example PCA latent space
#'
#' Example PCA latent space associated with the counts_gps single-cell data.
#'
#'
#' @format A matrix with 500 rows (cells) and 50 columns (principal components)
#' @examples data(latent_gps)
"latent_gps"

#' True cell type proportions
#'
#' True cell type proportions associated with the bulk_gps bulk data.
#'
#'
#' @format A matrix with 5 rows (5 bulk samples) and 9 columns (number of cell types)
#' @examples data(true_prop_gps)
"true_prop_gps"

#' Variable genes
#'
#' 2,000 variable genes associated with the counts_gps single-cell data.
#'
#'
#' @format A character vector containing 2,000 variable genes
#' @examples data(variable_genes_gps)
"variable_genes_gps"

#' meta data for 'counts_gps', the single-cell RNA-seq data
#'
#' data frame that contains the UMAP coordinates of each cell and cluster IDs
#'
#'
#' @format A data frame with 3 columns
#' @examples data(meta_data_gps)
"meta_data_gps"
